ecom_app/views/auth.py
"""
This module contains the views for the auth blueprint
"""

from flask import Blueprint, request, redirect, url_for, render_template, flash
from flask_login import login_user, logout_user, login_required
from werkzeug.security import check_password_hash

from ecom_app.service import seller_service


auth = Blueprint('auth', __name__)


@auth.route('/login')
def login():
    """
    This method is used to handle the GET request for the login page
    """
    return render_template('login.html')


@auth.route('/login', methods=['POST'])
def login_post():
    """
    This method is used to handle the POST request for the login page
    """
    email = request.form.get('email')
    password = request.form.get('password')

    seller = seller_service.get_seller_by_email(email)
    if not seller or not check_password_hash(seller.password, password):
        flash('Please check your login details and try again.')
        return redirect(url_for('auth.login'))

    login_user(seller, remember=True)
    return redirect(url_for('sellers.profile'))


@auth.route('/logout')
@login_required
def logout():
    """
    This method is used to handle the GET request for the logout page
    """
    logout_user()
    return redirect(url_for('auth.login'))

ecom_app/views/orders.py
"""
This module contains the views for the orders blueprint
"""

from flask import Blueprint, render_template
from flask_login import login_required


orders = Blueprint('orders', __name__)


@orders.route('/orders')
@login_required
def orders_():
    """
    This method is used to handle the GET request for the orders page
    """
    return render_template('orders.html')


@orders.route('/orders/edit', defaults={'order_id': None})
@orders.route('/orders/edit/<int:order_id>')
@login_required
def edit_order(order_id):
    """
    This method is used to handle the GET request for the edit order page
    :param order_id: The id of the order to edit
    """
    return render_template('edit_order.html')


@orders.route('/orders/add')
@login_required
def add_order():
    """
    This method is used to handle the GET request for the add order page
    """
    return render_template('add_order.html')

ecom_app/views/products.py
"""
This module contains the views for the products blueprint
"""

from flask import Blueprint, render_template
from flask_login import login_required


products = Blueprint('products', __name__)


@products.route('/products')
@login_required
def products_():
    """
    This method is used to handle the GET request for the products page
    """
    return render_template('products.html')


@products.route('/products/edit', defaults={'product_id': None})
@products.route('/products/edit/<int:product_id>')
@login_required
def edit_product(product_id):
    """
    This method is used to handle the GET request for the edit product page
    :param product_id: The id of the product to edit
    """
    return render_template('edit_product.html')


@products.route('/products/add')
@login_required
def add_product():
    """
    This method is used to handle the GET request for the add product page
    """
    return render_template('add_product.html')

ecom_app/views/sellers.py
"""
This module contains the views for the sellers blueprint
"""

from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_required, current_user


sellers = Blueprint('sellers', __name__)


@sellers.route('/')
@sellers.route('/profile')
@login_required
def profile():
    """
    This method is used to handle the GET request for the profile page
    """
    return render_template('profile.html')


@sellers.route('/edit_profile')
@login_required
def edit_profile():
    """
    This method is used to handle the GET request for the edit profile page
    """
    return render_template('edit_profile.html')


@sellers.route('/sellers')
@login_required
def sellers_():
    """
    This method is used to handle the GET request for the sellers page
    """
    if current_user.is_admin:
        return render_template('sellers.html')
    return 'You are not authorized to view this page', 403


@sellers.route('/sellers/edit', defaults={'seller_id': None})
@sellers.route('/sellers/edit/<int:seller_id>')
@login_required
def edit_seller(seller_id):
    """
    This method is used to handle the GET request for the edit seller page
    :param seller_id: The id of the seller to edit
    """
    if current_user.is_admin:
        return render_template('edit_seller.html')
    return 'You are not authorized to view this page', 403


@sellers.route('/sellers/add')
@login_required
def add_seller():
    """
    This method is used to handle the GET request for the add seller page
    """
    if current_user.is_admin:
        return render_template('add_seller.html')
    return 'You are not authorized to view this page', 403

ecom_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ecom</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
</head>
<body>
    {% block header %}
    {% endblock %}
    <div class="grid h-screen place-items-center">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

ecom_app/templates/orders.html
{% extends "base.html" %}
{% block header %}
<div class="absolute w-full pt-5">
    <div class="flex w-5/6 justify-between mx-auto">
        <div class="flex">
            <a class="border-2 rounded-l font-semibold p-2 pt-1 border-gray-500 m-0 hover:100" href="{{ url_for('products.products_') }}">Products</a>
            {% if not current_user.is_admin %}
            <a class="border-2 border-l-0 rounded-r font-semibold p-2 pt-1 border-gray-500 bg-slate-300 hover:bg-slate-200" href="{{ url_for('orders.orders_') }}">Orders</a>
            {% else %}
            <a class="border-2 border-x-0 font-semibold p-2 pt-1 border-gray-500 bg-slate-300 hover:bg-slate-200" href="{{ url_for('orders.orders_') }}">Orders</a>
            <a class="border-2 rounded-r font-semibold p-2 pt-1 border-gray-500 hover:bg-gray-100" href="{{ url_for('sellers.sellers_') }}">Sellers</a>
            {% endif %}
        </div>
        <div class="flex">
            <a class="border-2 rounded-l font-semibold p-2 pt-1 border-gray-500 m-0 hover:bg-gray-100" href="{{ url_for('sellers.profile') }}">My profile</a>
            <a class="border-2 border-l-0 rounded-r font-semibold p-2 pt-1 border-gray-500 hover:bg-gray-100" href="{{ url_for('auth.logout') }}">Log out</a>
        </div>
    </div>
</div>
{% endblock %}
{% block content %}
<div class="w-5/6 h-5/6  bg-slate-100 rounded">
    <div class="flex justify-between border-b-2 content-center py-1">
        <div class="flex">
            <div class="flex justify-between p-3 px-5">
                <label class="mr-6" for="status">Status</label>
                <select name="status" id="status">
                    <option value=""></option>
                    <option value="Complete">Complete</option>
                    <option value="In progress">In progress</option>
                </select>
            </div>
        </div>
        <div class="p-1.5 h-fit flex my-auto border-2 border-gray-500 rounded-full bg-gray-100 bg-white hover:bg-gray-100 mr-5" id="refresh_button">
            <svg height="22px" width="22px" viewBox="0 0 489.698 489.698">
                <g>
                    <g>
                        <path d="M468.999,227.774c-11.4,0-20.8,8.3-20.8,19.8c-1,74.9-44.2,142.6-110.3,178.9c-99.6,54.7-216,5.6-260.6-61l62.9,13.1
                   			c10.4,2.1,21.8-4.2,23.9-15.6c2.1-10.4-4.2-21.8-15.6-23.9l-123.7-26c-7.2-1.7-26.1,3.5-23.9,22.9l15.6,124.8
                   			c1,10.4,9.4,17.7,19.8,17.7c15.5,0,21.8-11.4,20.8-22.9l-7.3-60.9c101.1,121.3,229.4,104.4,306.8,69.3
                   			c80.1-42.7,131.1-124.8,132.1-215.4C488.799,237.174,480.399,227.774,468.999,227.774z"/>
                        <path d="M20.599,261.874c11.4,0,20.8-8.3,20.8-19.8c1-74.9,44.2-142.6,110.3-178.9c99.6-54.7,216-5.6,260.6,61l-62.9-13.1
                   			c-10.4-2.1-21.8,4.2-23.9,15.6c-2.1,10.4,4.2,21.8,15.6,23.9l123.8,26c7.2,1.7,26.1-3.5,23.9-22.9l-15.6-124.8
                   			c-1-10.4-9.4-17.7-19.8-17.7c-15.5,0-21.8,11.4-20.8,22.9l7.2,60.9c-101.1-121.2-229.4-104.4-306.8-69.2
                   			c-80.1,42.6-131.1,124.8-132.2,215.3C0.799,252.574,9.199,261.874,20.599,261.874z"/>
                    </g>
                </g>
            </svg>
        </div>
    </div>
    <div class="h-[93%] overflow-auto">
        <table class="w-full table-auto border-collapse border border-slate-500">
            <thead class="bg-slate-300">
            <tr class="">
                        <th class="border-x border-x-slate-500">Order ID</th>
                        <th class="border-x border-x-slate-500">Product</th>
                        <th class="border-x border-x-slate-500">Quantity</th>
                        <th class="border-x border-x-slate-500">Total cost</th>
                        <th class="border-x border-x-slate-500">Date</th>
                        <th class="border-x border-x-slate-500">Customer</th>
                        <th class="border-x border-x-slate-500">Status</th>
                        <th class="border-x border-x-slate-500">Actions</th>
                    </tr>
            </thead>
            <tbody id="tbody" class="">
            </tbody>
        </table>
    </div>
</div>
<div class="absolute bottom-[4%] right-[9%] mb-15">
    <button class="border-2 rounded font-semibold px-4 border-gray-500 m-0 hover:bg-gray-100" id="add">Add</button>
</div>
<script>
    let edit_function = function (id) {
        window.location.href = "{{ url_for('orders.edit_order') }}/" + id;
    }

    let delete_function = function (id) {
        if (confirm("Confirm deletion")) {
            $.ajax({
                url: "{{ url_for('rest_api.orderapi') }}" + "/" + id,
                type: "DELETE",
                success: function (data, textStatus, jqXHR) {
                    if (jqXHR.status === 200) {
                        document.location.reload(true);
                    } else {
                        alert(data.message);
                    }
                }
            });
        }
    }

    window.onload = function () {
        const queryString = window.location.search;
        const urlParams = new URLSearchParams(queryString);

        let status;

        if (urlParams.has('status')) {
            status = urlParams.get('status');
            document.getElementById('status').value = status;
        }

        $.ajax({
            url: "{{ url_for('rest_api.ordersapi') }}",
            type: "GET",
            data: {
                status: status
            },
            success: function (data) {
                let tbody = document.getElementById('tbody');
                tbody.innerHTML = "";

                data.forEach(function (order) {
                    let tr = document.createElement('tr');
                    tr.className = "bg-slate-200";

                    let id = document.createElement('td');
                    id.className = "p-1 border-x border-x-slate-500";
                    id.innerText = order.id;

                    let product = document.createElement('td');
                    product.className = "p-1 border-x border-x-slate-500";
                    product.innerText = order.product_name;

                    let quantity = document.createElement('td');
                    quantity.className = "p-1 border-x border-x-slate-500";
                    quantity.innerText = order.quantity;

                    let total_cost = document.createElement('td');
                    total_cost.className = "p-1 border-x border-x-slate-500";
                    total_cost.innerText = order.total;

                    let date = document.createElement('td');
                    date.className = "p-1 border-x border-x-slate-500";
                    //format date
                    let date_obj = new Date(order.date);
                    let date_str = date_obj.getDate() + "/" + (date_obj.getMonth() + 1) + "/" + date_obj.getFullYear();

                    date.innerText = date_str;

                    let customer_details = document.createElement('td');
                    customer_details.className = "p-1 border-x border-x-slate-500";
                    customer_details.innerText = order.customer_details;

                    let status = document.createElement('td');
                    status.className = "p-1 border-x border-x-slate-500";
                    status.innerText = order.status;

                    let actions = document.createElement('td');
                    actions.className = "p-1 border-x border-x-slate-500";
                    actions.innerHTML = `
                        <div class="flex justify-center">
                            <button onclick="edit_function(${order.id})" class="border-2 rounded-l font-semibold px-4 border-gray-500 m-0 hover:bg-gray-100">Edit</button>
                            <button class="border-2 border-l-0 rounded-r font-semibold px-2 border-gray-500 m-0 hover:bg-gray-100" onclick="delete_function(${order.id})">Delete</button>
                        </div>
                    `;

                    tr.appendChild(id);
                    tr.appendChild(product);
                    tr.appendChild(quantity);
                    tr.appendChild(total_cost);
                    tr.appendChild(date);
                    tr.appendChild(customer_details);
                    tr.appendChild(status);
                    tr.appendChild(actions);

                    tbody.appendChild(tr);


                });
            },
            error: function (xhr) {
                alert(xhr.responseJSON.message);
            }

        });
    }


    refresh_button = document.getElementById('refresh_button');
    refresh_button.addEventListener('click', function () {
        let status = document.getElementById('status').value;

        let url = "{{ url_for('orders.orders_') }}";

        if (status !== "") {
            url += "?status=" + status;
        }

        window.location.href = url;
    });

    add_button = document.getElementById('add');
    add_button.addEventListener('click', function () {
        window.location.href = "{{ url_for('orders.add_order') }}";
    });
</script>
{% endblock %}

ecom_app/templates/products.html
{% extends "base.html" %}
{% block header %}
<div class="absolute w-full pt-5">
    <div class="flex w-5/6 justify-between mx-auto">
        <div class="flex">
            <a class="border-2 rounded-l font-semibold p-2 pt-1 border-gray-500 m-0  bg-slate-300 hover:bg-slate-200" href="{{ url_for('products.products_') }}">Products</a>
            {% if not current_user.is_admin %}
            <a class="border-2 border-l-0 rounded-r font-semibold p-2 pt-1 border-gray-500 hover:bg-gray-100" href="{{ url_for('orders.orders_') }}">Orders</a>
            {% else %}
            <a class="border-2 border-x-0 font-semibold p-2 pt-1 border-gray-500 hover:bg-gray-100" href="{{ url_for('orders.orders_') }}">Orders</a>
            <a class="border-2 rounded-r font-semibold p-2 pt-1 border-gray-500 hover:bg-gray-100" href="{{ url_for('sellers.sellers_') }}">Sellers</a>
            {% endif %}
        </div>
        <div class="flex">
            <a class="border-2 rounded-l font-semibold p-2 pt-1 border-gray-500 m-0 hover:bg-gray-100" href="{{ url_for('sellers.profile') }}">My profile</a>
            <a class="border-2 border-l-0 rounded-r font-semibold p-2 pt-1 border-gray-500 hover:bg-gray-100" href="{{ url_for('auth.logout') }}">Log out</a>
        </div>
    </div>
</div>
{% endblock %}
{% block content %}
<div class="w-5/6 h-5/6  bg-slate-100 rounded">
    <div class="flex justify-between border-b-2 content-center py-1">
        <div class="flex">
            <div class="flex justify-between p-3 px-5">
                <span class="mr-6">Inventory range</span>
                <div class="">
                    <input class="w-12" name="inventory_from" id="inventory_from" type="number" value="">
                    ─
                    <input class="w-12" name="inventory_to" id="inventory_to" type="number" value="">
                </div>
            </div>
            <div class="flex justify-between p-3 px-5">
                <span class="mr-6">Ordered range</span>
                <div class="">
                    <input class="w-12" name="ordered_from" id="ordered_from" type="number" value="">
                    ─
                    <input class="w-12" name="ordered_to" id="ordered_to" type="number" value="">
                </div>
            </div>
        </div>
        <div class="p-1.5 h-fit flex my-auto border-2 border-gray-500 rounded-full bg-gray-100 bg-white hover:bg-gray-100 mr-5" id="refresh_button">
            <svg height="22px" width="22px" viewBox="0 0 489.698 489.698">
                <g>
                    <g>
                        <path d="M468.999,227.774c-11.4,0-20.8,8.3-20.8,19.8c-1,74.9-44.2,142.6-110.3,178.9c-99.6,54.7-216,5.6-260.6-61l62.9,13.1
                   			c10.4,2.1,21.8-4.2,23.9-15.6c2.1-10.4-4.2-21.8-15.6-23.9l-123.7-26c-7.2-1.7-26.1,3.5-23.9,22.9l15.6,124.8
                   			c1,10.4,9.4,17.7,19.8,17.7c15.5,0,21.8-11.4,20.8-22.9l-7.3-60.9c101.1,121.3,229.4,104.4,306.8,69.3
                   			c80.1-42.7,131.1-124.8,132.1-215.4C488.799,237.174,480.399,227.774,468.999,227.774z"/>
                        <path d="M20.599,261.874c11.4,0,20.8-8.3,20.8-19.8c1-74.9,44.2-142.6,110.3-178.9c99.6-54.7,216-5.6,260.6,61l-62.9-13.1
                   			c-10.4-2.1-21.8,4.2-23.9,15.6c-2.1,10.4,4.2,21.8,15.6,23.9l123.8,26c7.2,1.7,26.1-3.5,23.9-22.9l-15.6-124.8
                   			c-1-10.4-9.4-17.7-19.8-17.7c-15.5,0-21.8,11.4-20.8,22.9l7.2,60.9c-101.1-121.2-229.4-104.4-306.8-69.2
                   			c-80.1,42.6-131.1,124.8-132.2,215.3C0.799,252.574,9.199,261.874,20.599,261.874z"/>
                    </g>
                </g>
            </svg>
        </div>
    </div>
    <div class="h-[93%] overflow-auto">
        <table class="w-full table-auto border-collapse border border-slate-500">
            <thead class="bg-slate-300">
            <tr class="">
                        <th class="border-x border-x-slate-500">Name</th>
                        <th class="border-x border-x-slate-500">Description</th>
                        <th class="border-x border-x-slate-500">Price</th>
                        <th class="border-x border-x-slate-500">Inventory</th>
                        <th class="border-x border-x-slate-500">Ordered</th>
                        <th class="border-x border-x-slate-500">Actions</th>
                    </tr>
            </thead>
            <tbody id="tbody" class="">
            </tbody>
        </table>
    </div>
</div>
<div class="absolute bottom-[4%] right-[9%] mb-15">
    <button class="border-2 rounded font-semibold px-4 border-gray-500 m-0 hover:bg-gray-100" id="add">Add</button>
</div>
<script>
    let edit_function = function (id) {
        window.location.href = "{{ url_for('products.edit_product') }}/" + id;
    }

    let delete_function = function (id) {
        if (confirm("Confirm deletion")) {
            $.ajax({
                url: "{{ url_for('rest_api.productapi') }}" + "/" + id,
                type: "DELETE",
                success: function (data, textStatus, jqXHR) {
                    if (jqXHR.status === 200) {
                        document.location.reload(true);
                    } else {
                        alert(data.message);
                    }
                }
            });
        }
    }

    window.onload = function () {
        const queryString = window.location.search;
        const urlParams = new URLSearchParams(queryString);

        let inventory_from, inventory_to, ordered_from, ordered_to;

        if (urlParams.has('inventory_from')) {
            document.getElementById('inventory_from').value = urlParams.get('inventory_from');
            inventory_from = urlParams.get('inventory_from');
        }
        if (urlParams.has('inventory_to')) {
            document.getElementById('inventory_to').value = urlParams.get('inventory_to');
            inventory_to = urlParams.get('inventory_to');
        }
        if (urlParams.has('ordered_from')) {
            document.getElementById('ordered_from').value = urlParams.get('ordered_from');
            ordered_from = urlParams.get('ordered_from');
        }
        if (urlParams.has('ordered_to')) {
            document.getElementById('ordered_to').value = urlParams.get('ordered_to');
            ordered_to = urlParams.get('ordered_to');
        }

        $.ajax({
            url: "{{ url_for('rest_api.productsapi') }}",
            type: "GET",
            data: {
                inventory_from: inventory_from,
                inventory_to: inventory_to,
                ordered_from: ordered_from,
                ordered_to: ordered_to,
            },
            success: function (data) {
                let tbody = document.getElementById('tbody');
                tbody.innerHTML = "";

                data.forEach(function (product) {
                    let tr = document.createElement('tr');
                    tr.className = "bg-slate-200";

                    let name = document.createElement('td');
                    name.className = "p-1 border-x border-x-slate-500";
                    name.innerText = product.name;

                    let description = document.createElement('td');
                    description.className = "p-1 border-x border-x-slate-500";
                    description.innerText = product.description;

                    let price = document.createElement('td');
                    price.className = "p-1 border-x border-x-slate-500";
                    price.innerText = product.price;

                    let inventory = document.createElement('td');
                    inventory.className = "p-1 border-x border-x-slate-500";
                    inventory.innerText = product.inventory;

                    let ordered = document.createElement('td');
                    ordered.className = "p-1 border-x border-x-slate-500";
                    ordered.innerText = product.ordered;

                    let actions = document.createElement('td');
                    actions.className = "p-1 border-x border-x-slate-500";
                    actions.innerHTML = `
                        <div class="flex justify-center">
                            <button onclick="edit_function(${product.id})" class="border-2 rounded-l font-semibold px-4 border-gray-500 m-0 hover:bg-gray-100">Edit</button>
                            <button class="border-2 border-l-0 rounded-r font-semibold px-2 border-gray-500 m-0 hover:bg-gray-100" onclick="delete_function(${product.id})">Delete</button>
                        </div>
                    `;

                    tr.appendChild(name);
                    tr.appendChild(description);
                    tr.appendChild(price);
                    tr.appendChild(inventory);
                    tr.appendChild(ordered);
                    tr.appendChild(actions);

                    tbody.appendChild(tr);


                });
            },
            error: function (xhr) {
                alert(xhr.responseJSON.message);
            }

        });
    }


    refresh_button = document.getElementById('refresh_button');
    refresh_button.addEventListener('click', function () {
        let inventory_from = document.getElementById('inventory_from').value;
        let inventory_to = document.getElementById('inventory_to').value;
        let ordered_from = document.getElementById('ordered_from').value;
        let ordered_to = document.getElementById('ordered_to').value;

        let url = "{{ url_for('products.products_') }}";

        if (inventory_from !== "") {
            url += "?inventory_from=" + inventory_from;
        }
        if (inventory_to !== "") {
            url += "?inventory_to=" + inventory_to;
        }
        if (ordered_from !== "") {
            url += "?ordered_from=" + ordered_from;
        }
        if (ordered_to !== "") {
            url += "?ordered_to=" + ordered_to;
        }

        window.location.href = url;
    });

    add_button = document.getElementById('add');
    add_button.addEventListener('click', function () {
        window.location.href = "{{ url_for('products.add_product') }}";
    });
</script>
{% endblock %}

ecom_app/templates/sellers.html
{% extends "base.html" %}
{% block header %}
<div class="absolute w-full pt-5">
    <div class="flex w-5/6 justify-between mx-auto">
        <div class="flex">
            <a class="border-2 rounded-l font-semibold p-2 pt-1 border-gray-500 m-0 hover:bg-gray-100" href="{{ url_for('products.products_') }}">Products</a>
            <a class="border-2 border-x-0 font-semibold p-2 pt-1 border-gray-500 hover:bg-gray-100" href="{{ url_for('orders.orders_') }}">Orders</a>
            <a class="border-2 rounded-r font-semibold p-2 pt-1 border-gray-500 bg-slate-300 hover:bg-slate-200" href="{{ url_for('sellers.sellers_') }}">Sellers</a>
        </div>
        <div class="flex">
            <a class="border-2 rounded-l font-semibold p-2 pt-1 border-gray-500 m-0 hover:bg-gray-100" href="{{ url_for('sellers.profile') }}">My profile</a>
            <a class="border-2 border-l-0 rounded-r font-semibold p-2 pt-1 border-gray-500 hover:bg-gray-100" href="{{ url_for('auth.logout') }}">Log out</a>
        </div>
    </div>
</div>
{% endblock %}
{% block content %}
<div class="w-5/6 h-5/6  bg-slate-100 rounded">
    <div class="flex justify-between border-b-2 content-center py-1">
        <div class="flex">
        </div>
        <div class="p-1.5 h-fit flex my-auto border-2 border-gray-500 rounded-full bg-gray-100 bg-white hover:bg-gray-100 mr-5" id="refresh_button">
            <svg height="22px" width="22px" viewBox="0 0 489.698 489.698">
                <g>
                    <g>
                        <path d="M468.999,227.774c-11.4,0-20.8,8.3-20.8,19.8c-1,74.9-44.2,142.6-110.3,178.9c-99.6,54.7-216,5.6-260.6-61l62.9,13.1
                   			c10.4,2.1,21.8-4.2,23.9-15.6c2.1-10.4-4.2-21.8-15.6-23.9l-123.7-26c-7.2-1.7-26.1,3.5-23.9,22.9l15.6,124.8
                   			c1,10.4,9.4,17.7,19.8,17.7c15.5,0,21.8-11.4,20.8-22.9l-7.3-60.9c101.1,121.3,229.4,104.4,306.8,69.3
                   			c80.1-42.7,131.1-124.8,132.1-215.4C488.799,237.174,480.399,227.774,468.999,227.774z"/>
                        <path d="M20.599,261.874c11.4,0,20.8-8.3,20.8-19.8c1-74.9,44.2-142.6,110.3-178.9c99.6-54.7,216-5.6,260.6,61l-62.9-13.1
                   			c-10.4-2.1-21.8,4.2-23.9,15.6c-2.1,10.4,4.2,21.8,15.6,23.9l123.8,26c7.2,1.7,26.1-3.5,23.9-22.9l-15.6-124.8
                   			c-1-10.4-9.4-17.7-19.8-17.7c-15.5,0-21.8,11.4-20.8,22.9l7.2,60.9c-101.1-121.2-229.4-104.4-306.8-69.2
                   			c-80.1,42.6-131.1,124.8-132.2,215.3C0.799,252.574,9.199,261.874,20.599,261.874z"/>
                    </g>
                </g>
            </svg>
        </div>
    </div>
    <div class="h-[93%] overflow-auto">
        <table class="w-full table-auto border-collapse border border-slate-500">
            <thead class="bg-slate-300">
                <tr class="">
                    <th class="border-x border-x-slate-500">Name</th>
                    <th class="border-x border-x-slate-500">E-mail</th>
                    <th class="border-x border-x-slate-500">Phone</th>
                    <th class="border-x border-x-slate-500">Actions</th>
                </tr>
            </thead>
            <tbody id="tbody" class="">
            </tbody>
        </table>
    </div>
</div>
<div class="absolute bottom-[4%] right-[9%] mb-15">
    <button class="border-2 rounded font-semibold px-4 border-gray-500 m-0 hover:bg-gray-100" id="add">Add</button>
</div>
<script>
    let edit_function = function (id) {
        window.location.href = "{{ url_for('sellers.edit_seller') }}/" + id;
    }

    let delete_function = function (id) {
        if (confirm("Confirm deletion")) {
            $.ajax({
                url: "{{ url_for('rest_api.sellerapi') }}" + "/" + id,
                type: "DELETE",
                success: function (data, textStatus, jqXHR) {
                    if (jqXHR.status === 200) {
                        document.location.reload(true);
                    } else {
                        alert(data.message);
                    }
                }
            });
        }
    }

    window.onload = function () {
        const queryString = window.location.search;
        const urlParams = new URLSearchParams(queryString);

        $.ajax({
            url: "{{ url_for('rest_api.sellersapi') }}",
            type: "GET",
            success: function (data) {
                let tbody = document.getElementById('tbody');
                tbody.innerHTML = "";

                data.forEach(function (seller) {
                    let tr = document.createElement('tr');
                    tr.className = "bg-slate-200";

                    let name = document.createElement('td');
                    name.className = "p-1 border-x border-x-slate-500";
                    name.innerHTML = seller.name;

                    let email = document.createElement('td');
                    email.className = "p-1 border-x border-x-slate-500";
                    email.innerHTML = seller.email;

                    let phone = document.createElement('td');
                    phone.className = "p-1 border-x border-x-slate-500";
                    phone.innerHTML = seller.phone;

                    let actions = document.createElement('td');
                    actions.className = "p-1 border-x border-x-slate-500";
                    actions.innerHTML = `
                        <div class="flex justify-center">
                            <button onclick="edit_function(${seller.id})" class="border-2 rounded-l font-semibold px-4 border-gray-500 m-0 hover:bg-gray-100">Edit</button>
                            <button class="border-2 border-l-0 rounded-r font-semibold px-2 border-gray-500 m-0 hover:bg-gray-100" onclick="delete_function(${seller.id})">Delete</button>
                        </div>
                    `;

                    tr.appendChild(name);
                    tr.appendChild(email);
                    tr.appendChild(phone);
                    tr.appendChild(actions);

                    tbody.appendChild(tr);
                });
            },
            error: function (xhr) {
                alert(xhr.responseJSON.message);
            }

        });
    }


    refresh_button = document.getElementById('refresh_button');
    refresh_button.addEventListener('click', function () {
        window.location.href = "{{ url_for('sellers.sellers_') }}";
    });

    add_button = document.getElementById('add');
    add_button.addEventListener('click', function () {
        window.location.href = "{{ url_for('sellers.add_seller') }}";
    });
</script>
{% endblock %}